### PR TITLE
Add `module-info.java`

### LINKED ISSUE #9: Add `module-info.java`
Hi,

There hasn't been much activity in this repo for some time, so I hope you're still involved.

I'd like to request to make this a modular jar, as downstream projects would benefit from it.

Using multi-release jars, it is possible to do so while staying compatible with the pre-java 9 world (including Android). I've done this multiple times myself and would like to help out with a PR. However, I don't really know if you're using Maven or Gradle to build this lib, as the repo contains both.

Cheers!

### PR DESCRIPTION
**Pull request by overheadhunter**
Builds a multi-release jar (to remain downwards-compatible with Java 7) and adds a `module-info.java` for module-aware JDKs. Fixes #9.

To achieve this, the build tools needed some updates:
- Minimum JDK for building is now 11
- Bumped `at.favre.lib:common-parent` to 15 (for newer Maven plugin versions)
- Bumped mvnw to Maven 3.8.4

TODO
- [x] ~Rename package to avoid split package problems~ See #11
- [x] ~If a major release is required (due to changing package name), should it still target Java 7/8? Otherwise no MR-Jar is needed anyway~ 2.0.0 should still target 8+, so a MR-jar is required. This PR doesn't increase the target from 7 to 8, though. This can and should be done separately
- [ ] ~(separate PR) update distribution management, as bintray no longer accepts new packages (afaik)~ will be done by maintainer

### CODE REVIEW

**Comment by overheadhunter** [comment]
Build fails due to credentials not being available during PRs. Maybe PRs should skip jarsigner?

**Comment by patrickfav** [comment]
Very cool thanks a lot!

Yes, I made some builds public-PR ready, but it seems not this one. 
Overall looks good, will try it out in the next days.

Small thing though: please use, as in the overall project, spaces instead of tabs :)

**Comment by overheadhunter** [comment]
@patrickfav 

> please use, as in the overall project, spaces instead of tabs :)

Done 🙂

So what shall we do with the split package problem (see also linked issue)?

And what about bintray? I guess you haven't published anything since it closed its doors? Do you know [how to migrate to Maven Central](https://blog.sonatype.com/what-publishers-need-to-know-about-migrating-from-jcenter-/-bintray-to-the-central-repository)?

**Comment by overheadhunter** [comment]
@patrickfav Any chance you decide on the package name? Or if this project is stale, please let us know so we can fork it

**Comment by patrickfav** [comment]
Hi @overheadhunter sorry keeping you you wait. Thanks for showing me the split-package problem, honestly wasnt aware about that (since I mostly target super old versions of Java to be compatible).

Lets release a new major version (2.0.0), break the package and call it, as you suggested `at.favre.lib.hkdf`. I would like to keep targeting at least Java 8, so it can be used by everyone.

Suggestion:

* Lets merge this PR
* One new PR changing the package name (and maybe bump java to 8)
* One new PR fixing the publishing to maven central part

Would you like to help with the package part? I would handle the publishing part.

**Comment by overheadhunter** [comment]
@patrickfav Can you when we can expect a 2.0.0? Alternatively, there is no shame in admitting that you don't find time to do so and mark this project as stale. We just need to know how to deal with this downstream.

**Pull request merged**
